#' Synthetic binary trajectory data
#'
#' A simulated dataset with four planted latent groups, for demonstrating and
#' testing binary (LOGIT / `family = "binomial"`) group-based trajectory models.
#' It is entirely synthetic and domain-neutral; the true group labels are
#' included so recovery can be checked.
#'
#' The four groups follow distinct log-odds trajectories over ten occasions,
#' mixing polynomial orders: linear rising (group 1), cubic rise-peak-decline
#' (group 2), cubic decline-trough-recovery (group 3), and linear falling
#' (group 4). Generated by `data-raw/simulate-data.R` with a fixed seed.
#'
#' @format A data frame with 1500 rows and 24 columns:
#' \describe{
#'   \item{id}{Subject identifier.}
#'   \item{x1, x2}{Covariates, present but not driving the outcome.}
#'   \item{y1--y10}{Binary outcomes at occasions 1--10.}
#'   \item{t1--t10}{Occasion times.}
#'   \item{true_group}{Ground-truth group label (1--4); not used in fitting.}
#' }
#' @seealso [sim_continuous]
"sim_binary"

#' Synthetic continuous trajectory data
#'
#' A simulated dataset with four planted latent groups, for demonstrating and
#' testing continuous (CNORM / `family = "gaussian"`) group-based trajectory
#' models. Entirely synthetic and domain-neutral, with true group labels
#' included so recovery can be checked.
#'
#' The four groups follow distinct mean trajectories over ten occasions,
#' mixing polynomial orders: linear rising (group 1), cubic rise-peak-decline
#' (group 2), cubic decline-trough-recovery (group 3), and linear falling
#' (group 4), with Gaussian within-group noise. Separation is generous relative
#' to the noise so the single-start CNORM fit avoids local optima. Generated by
#' `data-raw/simulate-data.R` with a fixed seed.
#'
#' @format A data frame with 1200 rows and 24 columns:
#' \describe{
#'   \item{id}{Subject identifier.}
#'   \item{x1, x2}{Covariates, present but not driving the outcome.}
#'   \item{y1--y10}{Continuous outcomes at occasions 1--10.}
#'   \item{t1--t10}{Occasion times.}
#'   \item{true_group}{Ground-truth group label (1--4); not used in fitting.}
#' }
#' @seealso [sim_binary]
"sim_continuous"
