#' Synthetic binary trajectory data
#'
#' A simulated dataset with four planted latent groups, for demonstrating and
#' testing binary (LOGIT / `family = "binomial"`) group-based trajectory models.
#' It is entirely synthetic and domain-neutral; the true group labels are
#' included so recovery can be checked.
#'
#' The four groups follow distinct log-odds trajectories over four occasions:
#' stable-high, falling, rising, and stable-low. Group separation is wide
#' because binary data over few occasions is low-information. Generated by
#' `data-raw/simulate-data.R` with a fixed seed.
#'
#' @format A data frame with 1500 rows and 12 columns:
#' \describe{
#'   \item{id}{Subject identifier.}
#'   \item{x1, x2}{Covariates, present but not driving the outcome.}
#'   \item{y1, y2, y3, y4}{Binary outcomes at occasions 1--4.}
#'   \item{t1, t2, t3, t4}{Occasion times.}
#'   \item{true_group}{Ground-truth group label (1--4); not used in fitting.}
#' }
#' @seealso [sim_continuous]
"sim_binary"

#' Synthetic continuous trajectory data
#'
#' A simulated dataset with four planted latent groups, for demonstrating and
#' testing continuous (CNORM / `family = "gaussian"`) group-based trajectory
#' models. Entirely synthetic and domain-neutral, with true group labels
#' included so recovery can be checked.
#'
#' The four groups follow distinct mean trajectories over four occasions:
#' stable-high, falling, rising, and stable-low, with Gaussian within-group
#' noise. Separation is generous relative to the noise so the single-start CNORM
#' fit avoids local optima. Generated by `data-raw/simulate-data.R` with a fixed
#' seed.
#'
#' @format A data frame with 1200 rows and 12 columns:
#' \describe{
#'   \item{id}{Subject identifier.}
#'   \item{x1, x2}{Covariates, present but not driving the outcome.}
#'   \item{y1, y2, y3, y4}{Continuous outcomes at occasions 1--4.}
#'   \item{t1, t2, t3, t4}{Occasion times.}
#'   \item{true_group}{Ground-truth group label (1--4); not used in fitting.}
#' }
#' @seealso [sim_binary]
"sim_continuous"
